const $=id=>document.getElementById(id);
const ENGINE_URL='https://haven-engine.onrender.com';
const REQUEST_TIMEOUT_MS=15000;
let files={},lastJob=null;
function url(){return ENGINE_URL}
async function fetchWithTimeout(resource, options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(resource,{...options,signal:c.signal,cache:'no-store'})}finally{clearTimeout(t)}}
function add(text,kind){const d=document.createElement('div');d.className='msg '+kind;d.textContent=text;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
async function api(path,opts={}){let r;try{r=await fetchWithTimeout(url()+path,opts)}catch(e){if(e.name==='AbortError')throw new Error('The Haven Engine took too long to respond. Render may be waking up or the service is not deployed yet.');throw new Error('Network/CORS error reaching The Haven Engine.')}if(!r.ok)throw new Error(await r.text());return r}
async function connect(silent=false){$('connection').textContent='● Connecting…';$('connection').classList.remove('online');try{const r=await api('/health');const j=await r.json();$('connection').textContent='● Connected';$('connection').classList.add('online');if(!silent)add('Connected to The Haven Engine.','system');return j}catch(e){$('connection').textContent='● Offline';$('connection').classList.remove('online');if(!silent)add('The Haven Engine connection failed: '+e.message,'system');return null}}
$('send').onclick=async()=>{const text=$('prompt').value.trim();if(!text)return;add(text,'user');$('prompt').value='';try{const r=await api('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,files:Object.keys(files)})});const j=await r.json();add(j.reply,'assistant')}catch(e){add('The Haven Engine error: '+e.message,'system')}}
$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('send').click()}})
$('build').onclick=async()=>{const text=$('prompt').value.trim();if(!text){add('Describe what you want to build first.','system');return}try{const r=await api('/projects/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'haven-project',kind:'auto',request:text,files})});lastJob=await r.json();files=lastJob.files||{};renderFiles();$('download').disabled=false;add(`Build complete: ${Object.keys(files).length} files created.`,'assistant')}catch(e){add('Build failed: '+e.message,'system')}}
$('download').onclick=async()=>{if(!lastJob)return;try{const r=await api('/projects/'+encodeURIComponent(lastJob.project_id)+'/download');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='The-Haven-Project.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}catch(e){add('Download failed: '+e.message,'system')}}
$('uploadBtn').onclick=()=>$('files').click();
$('files').onchange=async()=>{for(const f of $('files').files){files[f.name]=await f.text().catch(()=> '[binary file uploaded; stored by engine]')}renderFiles();try{const fd=new FormData();for(const f of $('files').files)fd.append('files',f);await api('/uploads',{method:'POST',body:fd});add(`${$('files').files.length} file(s) uploaded to the Haven workspace.`,'assistant')}catch(e){add('Upload failed: '+e.message,'system')}}
function renderFiles(){$('filesList').innerHTML=Object.keys(files).length?Object.keys(files).map(x=>'<div>📄 '+x+'</div>').join(''):'No files yet.'}
renderFiles();connect();setInterval(()=>{if(!$('connection').classList.contains('online'))connect(true)},30000);
