const $=id=>document.getElementById(id);
const ENGINE_URL='https://haven-engine.onrender.com';
const REQUEST_TIMEOUT_MS=7000;
const MAX_RETRY_MS=300000;
let files={},lastJob=null,checking=false,retryMs=30000;
function setStatus(text,online=false,waking=false){const el=$('connection');if(!el)return;el.textContent='● '+text;el.classList.toggle('online',online);el.classList.toggle('waking',waking)}
function add(text,kind){const d=document.createElement('div');d.className='msg '+kind;d.textContent=text;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
async function fetchWithTimeout(url,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:c.signal,cache:'no-store',credentials:'omit',mode:'cors',headers:{Accept:'application/json',...(options.headers||{})}})}finally{clearTimeout(t)}}
async function api(path,opts={}){const u=ENGINE_URL+path+(path.includes('?')?'&':'?')+'_t='+Date.now();try{const r=await fetchWithTimeout(u,opts);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r}catch(e){if(e.name==='AbortError')throw new Error('The engine is asleep or unreachable. Render Free may need about a minute to wake.');if(String(e).includes('Failed to fetch')||String(e).includes('NetworkError'))throw new Error('The Haven Engine is unreachable right now.');throw e}}
async function checkEngine(announce=false){if(checking)return null;checking=true;try{const r=await api('/health');const j=await r.json();setStatus('Connected',true,false);retryMs=30000;if(announce)add('The Haven Engine is online and ready.','system');return j}catch(e){setStatus('Ready • Engine checks in background',false,false);if(announce)add(e.message,'system');return null}finally{checking=false}}
function scheduleCheck(){const delay=retryMs;retryMs=Math.min(Math.round(retryMs*1.8),MAX_RETRY_MS);setTimeout(()=>{if(!document.hidden)checkEngine(false);scheduleCheck()},delay)}
$('send').onclick=async()=>{const text=$('prompt').value.trim();if(!text)return;add(text,'user');$('prompt').value='';try{const r=await api('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,files:Object.keys(files)})});const j=await r.json();add(j.reply,'assistant');setStatus('Connected',true,false)}catch(e){add('The Haven Engine: '+e.message,'system');setStatus('Ready • Engine checks in background',false,false)}};
$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('send').click()}});
$('retry').onclick=()=>{retryMs=30000;checkEngine(true)};
$('build').onclick=async()=>{const text=$('prompt').value.trim();if(!text){add('Describe what you want to build first.','system');return}try{const r=await api('/projects/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'haven-project',kind:'auto',request:text,files})});lastJob=await r.json();files=lastJob.files||{};renderFiles();$('download').disabled=false;add(`Build complete: ${Object.keys(files).length} files created.`,'assistant');setStatus('Connected',true,false)}catch(e){add('Build failed: '+e.message,'system')}};
$('download').onclick=async()=>{if(!lastJob)return;try{const r=await api('/projects/'+encodeURIComponent(lastJob.project_id)+'/download');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='The-Haven-Project.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}catch(e){add('Download failed: '+e.message,'system')}};
$('uploadBtn').onclick=()=>$('files').click();
$('files').onchange=async()=>{const chosen=[...$('files').files];for(const f of chosen){files[f.name]=await f.text().catch(()=> '[binary file uploaded; stored by engine]')}renderFiles();try{const fd=new FormData();for(const f of chosen)fd.append('files',f);await api('/uploads',{method:'POST',body:fd});add(`${chosen.length} file(s) uploaded to the Haven workspace.`,'assistant')}catch(e){add('Upload saved in this browser; engine upload will retry when online.','system')}};
function renderFiles(){$('filesList').innerHTML=Object.keys(files).length?Object.keys(files).map(x=>'<div>📄 '+x.replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]))+'</div>').join(''):'No files yet.'}
// First paint is completely independent of Render. No spinner and no blocking connection state.
renderFiles();setStatus('Ready • Engine checks in background');checkEngine(false);scheduleCheck();
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkEngine(false)});
